[package]
name = "flappy"
version = "0.1.0"
authors = ["Tim Enders <enders.tim@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"